### ISSUE TITLE
UI does not open in browser (does work on Tor)

### ISSUE THREAD

**Issue by satsking** [benthecarman/mutiny-startos#11]
I tried opening Mutiny in my browser from services in StartOS using the .local address but I get an alert telling me site cannot be reached and that I should check if there is a typo. There isn't, obviously but I get this at the bottom:

DNS_PROBE_FINISHED_NXDOMAIN

I have gone into this using a tor browser and using the .onion address but I would like to use the .local as well. 

Anyone had this issue and how do I fix?

**Comment by benthecarman** [comment]
I am not too sure here, sounds like a networking issue for the start9 team

**Comment by satsking** [comment]
Yes, I think it’s actually a Start9 issue after a bit of thinking.
